# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list
    silent: true
  init:
    desc: setup tooling
    cmds:
      - npm install -g yo generator-code
      - npm install -g vsce
  new:
    desc: new extension pack (which will generate a new git repo)
    cmds:
      - yo code
  package:
    desc: package the extension
    cmds:
      - vsce package
  publish:
    desc: publish the packaged extension
    cmds:
      - vsce publish
